(defglobal ?*debug-mode* = TRUE)
(unwatch all)
(load "templates.clp")
(load-facts "board-game.fact")
(load-facts "main-features.fact")
(load-facts "players.fact")
(load-facts "best-players.fact")
(load-facts "secondary-kind.fact")
(load-facts "general-kind.fact")
