(defglobal ?*debug-mode* = TRUE)
(unwatch all)
(load "templates.clp")
(load "functions-print.clp")
(load "functions-ask.clp")
(load "functions.clp")
(load "main.clp")
(load "rules-questions.clp")
(load "rules-inference.clp")
(load "rules-result.clp")
(load "rules-final-configuration.clp")
(load "rules-retraction.clp")
(load-facts "board-game.fact")
(load-facts "general-kind.fact")
(load-facts "secondary-kind.fact")
(load-facts "thematic-environment.fact")